# generated by datamodel-codegen:
#   filename:  protocol.schema.json

from __future__ import annotations

from enum import Enum, IntEnum

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class ProtocolVersion(IntEnum):
    integer_1 = 1


class Kind(Enum):
    runtime_initialize = 'runtime.initialize'


class RuntimeInitialize(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind
    schemaDigest: constr(pattern=r'^[0-9a-f]{64}$')
    accountId: constr(max_length=128) | None


class Kind1(Enum):
    runtime_ready = 'runtime.ready'


class Capability(Enum):
    diagnostic = 'diagnostic'


class RuntimeReady(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind1
    schemaDigest: constr(pattern=r'^[0-9a-f]{64}$')
    capabilities: list[Capability] = Field(..., max_length=1)


class Kind2(Enum):
    runtime_health = 'runtime.health'


class RuntimeHealth(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind2


class Kind3(Enum):
    runtime_healthResult = 'runtime.healthResult'


class State(Enum):
    ready = 'ready'
    running = 'running'
    stopped = 'stopped'


class RuntimeHealthResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind3
    state: State


class Kind4(Enum):
    runtime_start = 'runtime.start'


class RuntimeStart(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind4
    sessionId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )


class Kind5(Enum):
    runtime_started = 'runtime.started'


class RuntimeStarted(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind5
    sessionId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )


class Kind6(Enum):
    runtime_stop = 'runtime.stop'


class RuntimeStop(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind6


class Kind7(Enum):
    runtime_stopped = 'runtime.stopped'


class RuntimeStopped(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind7


class Kind8(Enum):
    runtime_shutdown = 'runtime.shutdown'


class RuntimeShutdown(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind8


class Kind9(Enum):
    runtime_shutdownComplete = 'runtime.shutdownComplete'


class RuntimeShutdownComplete(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind9


class Kind10(Enum):
    runtime_error = 'runtime.error'


class Code(Enum):
    INVALID_MESSAGE = 'INVALID_MESSAGE'
    PROTOCOL_MISMATCH = 'PROTOCOL_MISMATCH'
    NOT_READY = 'NOT_READY'
    BUSY = 'BUSY'
    TIMEOUT = 'TIMEOUT'
    WORKER_EXITED = 'WORKER_EXITED'
    UNAUTHORIZED = 'UNAUTHORIZED'
    FORBIDDEN = 'FORBIDDEN'
    INTERNAL = 'INTERNAL'


class RuntimeError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind10
    code: Code
    message: constr(min_length=1, max_length=256)
    retryable: bool


class RuntimeMessage(
    RootModel[
        RuntimeInitialize
        | RuntimeReady
        | RuntimeHealth
        | RuntimeHealthResult
        | RuntimeStart
        | RuntimeStarted
        | RuntimeStop
        | RuntimeStopped
        | RuntimeShutdown
        | RuntimeShutdownComplete
        | RuntimeError
    ]
):
    root: (
        RuntimeInitialize
        | RuntimeReady
        | RuntimeHealth
        | RuntimeHealthResult
        | RuntimeStart
        | RuntimeStarted
        | RuntimeStop
        | RuntimeStopped
        | RuntimeShutdown
        | RuntimeShutdownComplete
        | RuntimeError
    ) = Field(..., title='RuntimeMessage')
