# generated by datamodel-codegen:
#   filename:  protocol.schema.json

from __future__ import annotations

from enum import Enum, IntEnum

from pydantic import BaseModel, ConfigDict, Field, RootModel, confloat, conint, constr


class ProtocolVersion(IntEnum):
    integer_3 = 3


class Kind(Enum):
    runtime_initialize = 'runtime.initialize'


class RuntimeInitialize(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind
    schemaDigest: constr(pattern=r'^[0-9a-f]{64}$')
    accountId: constr(max_length=128) | None


class Kind1(Enum):
    runtime_ready = 'runtime.ready'


class Capability(Enum):
    diagnostic = 'diagnostic'
    instructor_cursor = 'instructor_cursor'


class RuntimeReady(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind1
    schemaDigest: constr(pattern=r'^[0-9a-f]{64}$')
    capabilities: list[Capability] = Field(..., max_length=2)


class Kind2(Enum):
    runtime_health = 'runtime.health'


class RuntimeHealth(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind2


class Kind3(Enum):
    runtime_healthResult = 'runtime.healthResult'


class State(Enum):
    ready = 'ready'
    running = 'running'
    stopped = 'stopped'


class RuntimeHealthResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind3
    state: State


class Kind4(Enum):
    runtime_start = 'runtime.start'


class RuntimeStart(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind4
    sessionId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )


class Kind5(Enum):
    runtime_started = 'runtime.started'


class RuntimeStarted(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind5
    sessionId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )


class Kind6(Enum):
    runtime_stop = 'runtime.stop'


class RuntimeStop(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind6


class Kind7(Enum):
    runtime_stopped = 'runtime.stopped'


class RuntimeStopped(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind7


class Kind8(Enum):
    runtime_shutdown = 'runtime.shutdown'


class RuntimeShutdown(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind8


class Kind9(Enum):
    runtime_shutdownComplete = 'runtime.shutdownComplete'


class RuntimeShutdownComplete(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind9


class Kind10(Enum):
    runtime_error = 'runtime.error'


class Code(Enum):
    INVALID_MESSAGE = 'INVALID_MESSAGE'
    PROTOCOL_MISMATCH = 'PROTOCOL_MISMATCH'
    NOT_READY = 'NOT_READY'
    BUSY = 'BUSY'
    TIMEOUT = 'TIMEOUT'
    WORKER_EXITED = 'WORKER_EXITED'
    UNAUTHORIZED = 'UNAUTHORIZED'
    FORBIDDEN = 'FORBIDDEN'
    INTERNAL = 'INTERNAL'


class RuntimeError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind10
    code: Code
    message: constr(min_length=1, max_length=256)
    retryable: bool


class Rect(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: confloat(ge=-100000.0, le=100000.0)
    y: confloat(ge=-100000.0, le=100000.0)
    width: confloat(le=100000.0, gt=0.0)
    height: confloat(le=100000.0, gt=0.0)


class Target(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pid: conint(ge=1)
    window_id: conint(ge=0)
    title: constr(max_length=256)
    bounds: Rect


class Element(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(max_length=80)
    label: constr(max_length=256)
    role: constr(max_length=80)
    bounds: Rect
    value: constr(max_length=256)


class Observation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    target: Target
    captured_at: confloat(ge=0.0)
    elements: list[Element] = Field(..., max_length=200)
    complete: bool
    screenshot_id: (
        constr(
            pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
        )
        | None
    ) = None


class Gesture(Enum):
    point = 'point'
    click = 'click'
    drag = 'drag'
    type = 'type'
    scroll = 'scroll'


class Locale(Enum):
    en = 'en'
    vi = 'vi'


class Direction(Enum):
    up = 'up'
    down = 'down'
    left = 'left'
    right = 'right'


class Grounding(Enum):
    accessibility = 'accessibility'
    visual = 'visual'


class TeachingCue(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    observation_id: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    element_id: constr(max_length=80)
    gesture: Gesture
    caption: constr(min_length=1, max_length=400)
    locale: Locale
    source: Rect
    destination: Rect | None
    direction: Direction | None
    expires_at: confloat(ge=0.0)
    screenshot_id: (
        constr(
            pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
        )
        | None
    ) = None
    grounding: Grounding | None = None


class Outcome(Enum):
    confirmed = 'confirmed'
    mismatch = 'mismatch'
    unknown = 'unknown'


class Source(Enum):
    fresh_observation = 'fresh_observation'


class CheckResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    outcome: Outcome
    source: Source
    observation_id: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    checked_at: confloat(ge=0.0)
    message: constr(max_length=256)


class Observation1(Enum):
    unknown = 'unknown'
    available = 'available'
    unavailable = 'unavailable'


class Model(Enum):
    unconfigured = 'unconfigured'
    ready = 'ready'
    unavailable = 'unavailable'


class Reason(Enum):
    none = 'none'
    connect_model = 'connect_model'
    observe_again = 'observe_again'
    retry_plan = 'retry_plan'


class Screen(Enum):
    unknown = 'unknown'
    available = 'available'
    unavailable = 'unavailable'


class Accessibility(Enum):
    unknown = 'unknown'
    available = 'available'
    unavailable = 'unavailable'


class Readiness(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    observation: Observation1
    model: Model
    reason: Reason
    screen: Screen
    accessibility: Accessibility


class Phase(Enum):
    observation = 'observation'
    model = 'model'
    grounding = 'grounding'


class Timing(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    phase: Phase
    elapsed_ms: confloat(ge=0.0, le=3600000.0)


class Kind11(Enum):
    runtime_listTargets = 'runtime.listTargets'


class RuntimeListTargets(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind11


class Kind12(Enum):
    runtime_targetsResult = 'runtime.targetsResult'


class Kind13(Enum):
    runtime_selectTarget = 'runtime.selectTarget'


class RuntimeSelectTarget(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind13
    pid: conint(ge=1)
    windowId: conint(ge=0)


class Kind14(Enum):
    runtime_targetSelected = 'runtime.targetSelected'


class Kind15(Enum):
    runtime_observe = 'runtime.observe'


class RuntimeObserve(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind15


class Kind16(Enum):
    runtime_observationResult = 'runtime.observationResult'


class Kind17(Enum):
    runtime_explain = 'runtime.explain'


class RuntimeExplain(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind17
    elementId: constr(max_length=80)
    gesture: Gesture
    caption: constr(min_length=1, max_length=400)
    locale: Locale
    destinationId: constr(max_length=80) | None
    direction: Direction | None


class Kind18(Enum):
    runtime_explanationResult = 'runtime.explanationResult'


class Kind19(Enum):
    runtime_check = 'runtime.check'


class RuntimeCheck(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind19
    cueId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    label: constr(max_length=256)
    expected: constr(max_length=256)


class Kind20(Enum):
    runtime_checkResult = 'runtime.checkResult'


class Kind21(Enum):
    runtime_presentationAck = 'runtime.presentationAck'


class RuntimePresentationAck(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind21
    cueId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )


class Kind22(Enum):
    runtime_presentationAckResult = 'runtime.presentationAckResult'


class Kind23(Enum):
    runtime_configure = 'runtime.configure'


class ModelConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    origin: constr(max_length=2048)
    grant: constr(min_length=64, max_length=64)
    model: constr(min_length=1, max_length=128)


class RuntimeConfigure(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind23
    storageRoot: constr(min_length=1, max_length=4096)
    modelConfig: ModelConfig | None


class Kind24(Enum):
    runtime_configured = 'runtime.configured'


class RuntimeConfigured(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind24


class Kind25(Enum):
    runtime_ask = 'runtime.ask'


class RuntimeAsk(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind25
    question: constr(min_length=1, max_length=1000)
    locale: Locale


class Kind26(Enum):
    runtime_askResult = 'runtime.askResult'


class Kind27(Enum):
    runtime_refreshCue = 'runtime.refreshCue'


class RuntimeRefreshCue(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind27


class Kind28(Enum):
    runtime_cueRefreshResult = 'runtime.cueRefreshResult'


class Status(Enum):
    running = 'running'
    awaiting_confirmation = 'awaiting_confirmation'
    paused = 'paused'
    completed = 'completed'


class Step(RootModel[constr(min_length=1, max_length=400)]):
    root: constr(min_length=1, max_length=400)


class Journey(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    index: conint(ge=0, le=3)
    status: Status
    message: constr(max_length=400)
    steps: list[Step] = Field(..., max_length=3, min_length=1)


class Kind29(Enum):
    runtime_planControl = 'runtime.planControl'


class Action(Enum):
    pause = 'pause'
    resume = 'resume'
    confirm = 'confirm'


class RuntimePlanControl(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind29
    action: Action


class Kind30(Enum):
    runtime_planControlResult = 'runtime.planControlResult'


class PreparedInstruction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    preparationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    utteranceId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    target: Target
    expiresAt: constr(min_length=20, max_length=40)


class Kind31(Enum):
    runtime_prepareInstruction = 'runtime.prepareInstruction'


class RuntimePrepareInstruction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind31
    utteranceId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )


class Kind32(Enum):
    runtime_instructionPrepared = 'runtime.instructionPrepared'


class RuntimeInstructionPrepared(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind32
    prepared: PreparedInstruction


class Kind33(Enum):
    runtime_startGuidance = 'runtime.startGuidance'


class ModelConfig1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    origin: constr(max_length=2048)
    grant: constr(pattern=r'^[0-9a-f]{64}$')
    model: constr(min_length=1, max_length=128)


class RuntimeStartGuidance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind33
    utteranceId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    preparationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    instruction: constr(min_length=1, max_length=2000)
    locale: Locale
    modelConfig: ModelConfig1


class Kind34(Enum):
    runtime_guidanceStarted = 'runtime.guidanceStarted'


class TeachingState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    revision: conint(ge=0)
    session_id: (
        constr(
            pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
        )
        | None
    )
    targets: list[Target] = Field(..., max_length=100)
    target: Target | None
    observation: Observation | None
    cue: TeachingCue | None
    check: CheckResult | None
    journey: Journey | None = None
    readiness: Readiness | None = None
    timings: list[Timing] | None = Field(None, max_length=200)


class RuntimeListTargetsResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind12
    state: TeachingState


class RuntimeSelectTargetResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind14
    state: TeachingState


class RuntimeObserveResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind16
    state: TeachingState


class RuntimeExplainResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind18
    state: TeachingState


class RuntimeCheckResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind20
    state: TeachingState


class RuntimePresentationAckResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind22
    state: TeachingState


class RuntimeAskResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind26
    state: TeachingState


class RuntimeRefreshCueResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind28
    state: TeachingState


class RuntimePlanControlResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind30
    state: TeachingState


class RuntimeGuidanceStarted(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: ProtocolVersion
    requestId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    correlationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    generationId: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    kind: Kind34
    state: TeachingState


class RuntimeMessage(
    RootModel[
        RuntimeInitialize
        | RuntimeReady
        | RuntimeHealth
        | RuntimeHealthResult
        | RuntimeStart
        | RuntimeStarted
        | RuntimeStop
        | RuntimeStopped
        | RuntimeShutdown
        | RuntimeShutdownComplete
        | RuntimeError
        | RuntimeListTargets
        | RuntimeListTargetsResult
        | RuntimeSelectTarget
        | RuntimeSelectTargetResult
        | RuntimeObserve
        | RuntimeObserveResult
        | RuntimeExplain
        | RuntimeExplainResult
        | RuntimeCheck
        | RuntimeCheckResult
        | RuntimePresentationAck
        | RuntimePresentationAckResult
        | RuntimeConfigure
        | RuntimeConfigured
        | RuntimeAsk
        | RuntimeAskResult
        | RuntimeRefreshCue
        | RuntimeRefreshCueResult
        | RuntimePlanControl
        | RuntimePlanControlResult
        | RuntimePrepareInstruction
        | RuntimeInstructionPrepared
        | RuntimeStartGuidance
        | RuntimeGuidanceStarted
    ]
):
    root: (
        RuntimeInitialize
        | RuntimeReady
        | RuntimeHealth
        | RuntimeHealthResult
        | RuntimeStart
        | RuntimeStarted
        | RuntimeStop
        | RuntimeStopped
        | RuntimeShutdown
        | RuntimeShutdownComplete
        | RuntimeError
        | RuntimeListTargets
        | RuntimeListTargetsResult
        | RuntimeSelectTarget
        | RuntimeSelectTargetResult
        | RuntimeObserve
        | RuntimeObserveResult
        | RuntimeExplain
        | RuntimeExplainResult
        | RuntimeCheck
        | RuntimeCheckResult
        | RuntimePresentationAck
        | RuntimePresentationAckResult
        | RuntimeConfigure
        | RuntimeConfigured
        | RuntimeAsk
        | RuntimeAskResult
        | RuntimeRefreshCue
        | RuntimeRefreshCueResult
        | RuntimePlanControl
        | RuntimePlanControlResult
        | RuntimePrepareInstruction
        | RuntimeInstructionPrepared
        | RuntimeStartGuidance
        | RuntimeGuidanceStarted
    ) = Field(..., title='RuntimeMessage')
